### PR TITLE
Add duration predictor training

### PR DESCRIPTION
**Pull request by ductho9799**
Hello p0p4k! Your repository is very awesome. I trained VITS2 with your code on my private data. I have implemented duration predictor training code. You can test it.

### CODE REVIEW

**Comment by p0p4k** [comment]
> I have implemented duration predictor training code. You can test it.

Hi, I will check and review the code ASAP.
> I trained VITS2 with your code on my private data. 

How are the results? Can you share some samples?  No need to share the weights, just wav samples if possible, to see the output quality. Thanks!

**Comment by p0p4k** [comment]
Interesting! Can I add your samples on README of this repo? I still would advice to add discriminator and train the model.

**Comment by egorsmkv** [comment]
@ductho9799 hello. What was improved in speech? I'm curious just pronunciation or other characteristics of the voice?

**Comment by p0p4k** [comment]
@ductho9799 change access of your drive file. Thanks.

**Comment by p0p4k** [comment]
Thanks for sharing the checkpoints! Samples sound not bad! Can you train the latest code with duration discriminator and HIFIGan Discriminator (multiperiod disc) with nosdp?

**Comment by p0p4k** [comment]
I am booting a cloud GPU right now to train as well. I want to check if the duration discriminator is working or not. (no nan, inf values, etc)

**Comment by p0p4k** [comment]
If the training works well, I will share the checkpoints so you can continue to train on that; else will try to fix the code before weekend.

**Comment by p0p4k** [comment]
@ductho9799 checkpoints are on main page readme. Good luck!

**Comment by kingkong135** [comment]
> I trained VITS-2 from-scratch. Here is my configs: [vits-2-configs.json](https://drive.google.com/file/d/1ZnBSFRtRDrnkWi-Cjyf8_qBmrOBoGiDh/view?usp=drive_link). I trained it on 4 RTX 3090 24 GVRAM



@ductho9799 Can you share file symbols.py, i trained in infore dataset but result not good. I used config like you.  :((. All config, model and train.log in [drive](https://drive.google.com/drive/folders/1fHdk1PodCiZ-BD9N8M7OUVfBWzACMM0u?usp=sharing). Can you give me some advice? Thank you very much.

**Comment by ngocson1804** [comment]
@ductho9799 have you tried with an external embedding extractor?

**Comment by HuuHuy227** [comment]
> @ductho9799 have you tried with an external embedding extractor?

Did you mean bert-vit2s?

**Comment by TalapMukhamejan** [comment]
@ductho9799 Can you please share your symbols? Cause while trying to inference it, I am getting this error
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([184, 192]) from checkpoint, the shape in current model is torch.Size([178, 192]).

**Comment by ml-maddi** [comment]
Hi @p0p4k , thanks for this great repository. I have trained the vits2 model for Bangla language for 100k steps. I have got some promising results. You can view the audio samples in this link [Bangla Audio Samples](https://ml-maddi.github.io/vits2_pytorch/)

**Pull request closed without merging**
