### PR TITLE
fix: pep8 and new librosa

### PR DESCRIPTION
**Pull request by shigabeev**
Hello!

The existing versions of Numpy and Librosa in the repository are outdated, leading to installation challenges. I've updated the mel extraction function to ensure compatibility with the newer versions of Librosa. Additionally, I've bumped the versions of both Numpy and Scipy.

The specific change can be found in mel_processing.py

Previously, the code was:

````
mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
````

I've modified it to:

````
mel = librosa_mel_fn(sr=sampling_rate, n_fft=n_fft, n_mels=num_mels, fmin=fmin, fmax=fmax)
````

Moreover, I've run autopep8 on all .py files to ensure consistent indentation throughout the codebase.

Thanks for considering my changes!

### CODE REVIEW

**Comment by p0p4k** [comment]
HI can you re-do this PR with latest patch? Thanks.

**Comment by shigabeev** [comment]
Sure. Later today

**Comment by shigabeev** [comment]
Done

**Comment by shigabeev** [comment]
I guess PEP8 should be done by you. Check the newest PR

**Pull request closed without merging**
