### PR TITLE
train files for vctk 0.92

### PR DESCRIPTION
**Pull request by AWAS666**
changes I made to the original file list to be compatible with the newest vctk 0.92 version, not sure if those should be kept seperate or merged with the original ones.

tldr:
I made a little script that deleted any entries which have no audio files

### CODE REVIEW

**Comment by I8dNLo** [comment]
You also can provide updated config to run this on actual vctk dataset

**Comment by AWAS666** [comment]
> You also can provide updated config to run this on actual vctk dataset

oh it's just adding in the new file paths, depending on whet ever these should be the main files or not it can be added, otherwise just rename them to replace the current

**Comment by p0p4k** [comment]
Thanks for the updated filelist!

**Comment by AWAS666** [comment]
> Thanks for the updated filelist!

should we update the original files, since these are currently new ones?

**Comment by p0p4k** [comment]
We can keep both versions and add a new config file for vctk_new ? thoguhts?

**Comment by p0p4k** [comment]
What if we add a function in dataloader that skips missing files and stores them in a text file under the logs folder of the training for the user to later verify that? If number of files available is less than ~30, we can assert error.

**Comment by I8dNLo** [comment]
It could be just a warning to say like 'Looks like you are using old version of dataset'

**Comment by p0p4k** [comment]
> It could be just a warning to say like 'Looks like you are using old version of dataset'

Good practice is to generalize your code for future versions. But for now a simple warning like this could work too.

**Comment by AWAS666** [comment]
I mean the current is perfectly fine for anyone using their own dataset, it's just about the vctk versioning.

**Comment by p0p4k** [comment]
Cool. Did anyone train back yet? How are the results?

**Comment by AWAS666** [comment]
I've reset after some first trial and error runs to see what dataset works.
Currently sitting at 124 epochs and the sample in tensorboard sounds decent.

Though I cant do any inference as I've moved to windows and I got no espeak there :(

**Comment by p0p4k** [comment]
> I've reset after some first trial and error runs to see what dataset works.
> Currently sitting at 124 epochs and the sample in tensorboard sounds decent.
> 
> Though I cant do any inference as I've moved to windows and I got no espeak there :(

Thanks for your feedback! Good to see something positive about multispeaker training. You can always infer on Google Collab for free, temporarily.

**Pull request merged**
